{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Use phot-griz environment (updated photutils)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# General imports\n",
    "import os\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Segmentation\n",
    "from astropy.io import fits\n",
    "from photutils.segmentation import SourceFinder, make_2dgaussian_kernel, SourceCatalog\n",
    "from photutils.background import Background2D, MedianBackground\n",
    "from astropy.convolution import convolve\n",
    "\n",
    "# grizli\n",
    "from grizli.model import GrismFLT\n",
    "\n",
    "os.chdir(\"/Users/keith/astr/research_astr/summer-roman-project/new-sims/fits\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "33588532a6874c8cb463abc329cea10e",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Deblending:   0%|          | 0/6281 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Process direct image and produce segmentation map\n",
    "\n",
    "# Open image\n",
    "direct_file = \"rotated_GRS_FOV0_roll0_dx0_dy0_SCA1_direct_final.fits\"\n",
    "seg_file = \"seg.fits\"\n",
    "direct_fits = fits.open(direct_file)\n",
    "data, header = (direct_fits[1].data, direct_fits[1].header)\n",
    "\n",
    "\n",
    "# Subtract background\n",
    "bkg_estimator = MedianBackground()\n",
    "bkg = Background2D(data, (511,511), filter_size=(3,3), bkg_estimator=bkg_estimator)\n",
    "data -= bkg.background\n",
    "\n",
    "# Convolve image\n",
    "kernel = make_2dgaussian_kernel(3.0, 5)\n",
    "convolved_data = convolve(data, kernel)\n",
    "\n",
    "# Instantiate the SourceFinder and set threshold\n",
    "finder = SourceFinder(npixels=7, nlevels=32, contrast=0.001)\n",
    "threshold = 2 * bkg.background_rms\n",
    "\n",
    "seg_map = finder(convolved_data, threshold)\n",
    "\n",
    "# Save seg_map as fits\n",
    "fits.writeto(seg_file, seg_map, header=header,overwrite=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create Catalog\n",
    "cat = SourceCatalog(data, seg_map, convolved_data=convolved_data)\n",
    "cat.add_extra_property('id', cat.label, overwrite=True)\n",
    "cat.add_extra_property('mag', cat.segment_flux, overwrite=True)\n",
    "cat.add_extra_property('x_flt', cat.xcentroid, overwrite=True)\n",
    "cat.add_extra_property('y_flt', cat.ycentroid, overwrite=True)\n",
    "\n",
    "columns = ['id', 'x_flt', 'y_flt', 'mag', 'area', 'semimajor_sigma', 'semiminor_sigma',\n",
    "           'orientation', 'eccentricity', 'min_value', 'max_value']\n",
    "tbl = cat.to_table(columns)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Mask a box on the sky\n",
    "mask = (abs(tbl[\"x_flt\"] - 2370) < 100) & (abs(tbl[\"y_flt\"] - 3350) < 100)\n",
    "mask_2 = (abs(tbl[\"x_flt\"] - 2000) < 500) & (abs(tbl[\"y_flt\"] - 250) < 100)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "Image cutout: x=slice(0, 4088, None), y=slice(0, 4088, None) [Out of range]\n",
      "rotated_GRS_FOV0_roll0_dx0_dy0_SCA1_direct_final.fits / Pad ref HDU with 576 pixels\n",
      "rotated_GRS_FOV0_roll0_dx0_dy0_SCA1_direct_final.fits / blot segmentation seg.fits[0]\n",
      "The following task in the stsci.skypac package can be run with TEAL:\n",
      "                                    skymatch                                    \n",
      "The following tasks in the drizzlepac package can be run with TEAL:\n",
      "    astrodrizzle       config_testbed      imagefindpars           mapreg       \n",
      "       photeq            pixreplace           pixtopix            pixtosky      \n",
      "  refimagefindpars       resetbits          runastrodriz          skytopix      \n",
      "     tweakback            tweakreg           updatenpol\n",
      "Using default C-based coordinate transformation...\n",
      "Using default C-based coordinate transformation...\n",
      "Image cutout: x=slice(0, 4088, None), y=slice(0, 4088, None) [Out of range]\n",
      "rotated_GRS_FOV0_roll0_dx0_dy0_SCA1_direct_final.fits / Pad ref HDU with 576 pixels\n",
      "rotated_GRS_FOV0_roll0_dx0_dy0_SCA1_direct_final.fits / blot segmentation seg.fits[0]\n",
      "Using default C-based coordinate transformation...\n",
      "Using default C-based coordinate transformation...\n"
     ]
    }
   ],
   "source": [
    "# Instantiate the GrismFLT object\n",
    "sim_fov0 = GrismFLT(direct_file=direct_file, seg_file=seg_file)\n",
    "sim_fov0_2 = GrismFLT(direct_file=direct_file, seg_file=seg_file)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "dyc: [16 16 16 ... 10 10 10] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "dyc: [15 15 15 ...  9  9  9] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "dyc: [15 15 15 ...  9  9  9] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "dyc: [15 15 15 ...  9  9  9] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "dyc: [14 14 14 ...  8  8  8] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "dyc: [14 14 14 ...  8  8  8] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "dyc: [14 14 14 ...  9  9  9] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "dyc: [14 14 14 ...  8  8  8] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "dyc: [14 14 14 ...  8  8  8] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "dyc: [13 13 13 ...  8  8  8] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "dyc: [13 13 13 ...  8  8  8] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "dyc: [14 14 14 ...  8  8  8] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "dyc: [13 13 13 ...  8  8  8] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "dyc: [12 12 12 ...  7  7  7] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n"
     ]
    }
   ],
   "source": [
    "sim_fov0.compute_full_model(ids=tbl['id'][mask], mags=tbl['mag'][mask], mag_limit=28)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "dyc: [63 63 63 ... 41 41 41] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.134)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 88 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [62 62 62 ... 39 39 39] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.147)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 87 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [61 61 61 ... 39 39 39] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.153)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 86 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [63 63 63 ... 41 41 41] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.160)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 88 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [65 65 65 ... 43 43 43] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.166)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 90 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [62 62 62 ... 40 40 40] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.172)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 87 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [66 66 66 ... 44 44 44] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.178)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 91 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 42 42 42] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.185)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 42 42 42] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.191)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 42 42 42] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.197)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [66 66 66 ... 45 45 45] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.203)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 91 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [63 63 63 ... 40 40 40] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.209)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 88 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [62 62 62 ... 39 39 39] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.216)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 87 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [62 62 62 ... 40 40 40] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.222)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 87 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [65 65 65 ... 43 43 43] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.228)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 90 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [61 61 61 ... 39 39 39] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.234)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 86 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [63 63 63 ... 41 41 41] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.240)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 88 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [61 61 61 ... 39 39 39] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.246)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 86 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [63 63 63 ... 42 42 42] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.268)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 88 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 42 42 42] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.280)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [62 62 62 ... 40 40 40] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.286)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 87 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 43 43 43] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.292)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 42 42 42] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.298)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [61 61 61 ... 39 39 39] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.304)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 86 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 42 42 42] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.310)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [65 65 65 ... 44 44 44] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.316)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 90 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [62 62 62 ... 40 40 40] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.322)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 87 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [65 65 65 ... 44 44 44] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.328)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 90 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 43 43 43] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.334)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [65 65 65 ... 44 44 44] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.340)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 90 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [60 60 60 ... 38 38 38] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.347)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 85 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [61 61 61 ... 39 39 39] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.353)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 86 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 43 43 43] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.359)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [63 63 63 ... 42 42 41] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.365)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 88 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [63 63 63 ... 42 42 42] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.377)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 88 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [62 62 62 ... 41 41 41] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.383)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 87 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [61 61 61 ... 39 39 39] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.389)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 86 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [62 62 62 ... 41 41 41] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.395)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 87 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 43 43 43] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.401)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [62 61 61 ... 40 40 40] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.413)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 87 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [61 61 61 ... 40 40 40] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.419)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 86 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [61 61 61 ... 39 39 39] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.425)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 86 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 44 44 44] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.432)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [62 62 62 ... 40 40 40] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.438)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 87 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [60 60 60 ... 38 38 38] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.444)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 85 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [63 63 63 ... 42 42 42] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.450)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 88 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [62 61 61 ... 40 40 40] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.456)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 87 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 43 43 43] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.462)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [62 62 62 ... 40 40 40] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.468)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 87 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [63 63 63 ... 42 42 42] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.474)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 88 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 43 43 43] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.480)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [61 61 61 ... 40 40 40] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.486)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 86 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 43 43 43] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.492)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [63 63 63 ... 42 42 42] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.498)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 88 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 43 43 43] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.510)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [63 63 63 ... 42 42 42] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.516)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 88 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 43 43 43] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.522)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [63 63 63 ... 42 42 42] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.533)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 88 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [59 59 59 ... 38 38 38] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.540)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 84 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [63 63 63 ... 42 42 42] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.546)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 88 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [61 61 61 ... 40 40 40] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.552)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 86 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 43 43 43] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.558)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [63 63 63 ... 43 43 42] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.564)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 88 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [61 61 61 ... 40 40 40] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.570)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 86 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [62 62 62 ... 41 41 41] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.576)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 87 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [60 60 60 ... 39 39 39] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.582)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 85 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [61 61 61 ... 40 40 40] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.588)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 86 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [65 65 65 ... 43 43 43] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.594)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 90 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [65 65 65 ... 43 43 43] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.600)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 90 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 42 42 42] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.606)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 42 42 42] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.613)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 43 43 43] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.619)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 43 43 43] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.625)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [64 64 64 ... 43 43 43] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.631)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 89 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [61 61 61 ... 39 39 39] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.637)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 86 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n",
      "dyc: [63 63 63 ... 42 42 42] \n",
      "self.x0[0]: 25 \n",
      "self.dxpix: [  25   26   27 ... 1622 1623 1624] \n",
      "\n",
      "\n",
      "########################################## \n",
      "# ! Exception (2024-06-18 16:46:39.654)\n",
      "#\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 419, in process_config\n",
      "# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]\n",
      "# !                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "# !IndexError: index 88 is out of bounds for axis 0 with size 52\n",
      "# !\n",
      "# !During handling of the above exception, another exception occurred:\n",
      "# !\n",
      "# !Traceback (most recent call last):\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 3177, in compute_model_orders\n",
      "# !    beam = GrismDisperser(id=id,\n",
      "# !           ^^^^^^^^^^^^^^^^^^^^^\n",
      "# !  File \"/Users/keith/miniconda3/envs/phot-griz/lib/python3.12/site-packages/grizli/model.py\", line 289, in __init__\n",
      "# !    self.process_config()\n",
      "# !IndexError\n",
      "# !\n",
      "######################################### \n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "sim_fov0_2.compute_full_model(ids=tbl['id'][mask_2], mags=tbl['mag'][mask_2], mag_limit=28)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Text(0.5, 1.0, 'Cutout Close to Origin')"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAjAAAACyCAYAAABcFvWVAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8fJSN1AAAACXBIWXMAAA9hAAAPYQGoP6dpAABC1UlEQVR4nO3deVhTV/oH8C8gYQ+I7CIo4qC41CluUYvUBVS0rlXHTsW6VCzaKhYt6lS0tjjaulVFbTton5+44Gi1YlVksxY6daMqriiIrSxuLMoqeX9/YG6TkISAYIy+n+fJAznn3Hvfe0Hzcu455xoQEYExxhhjTI8Y6joAxhhjjLH64gSGMcYYY3qHExjGGGOM6R1OYBhjjDGmdziBYYwxxpje4QSGMcYYY3qHExjGGGOM6R1OYBhjjDGmdziBYYwxxpje4QSGMcbYC8HAwAARERG6DkNvJScnw8DAAMnJyfXeNjs7GwYGBti2bVujx9VUOIFhjLHn6MaNG5gxYwY8PDxgamoKsViMPn36YN26dSgrK6v3/lJTUxEREYHCwsLGD1bJpUuXEBERgezs7Hptl56ejn/+859o1aoVTExMYGtri4EDByI6OhrV1dVNE2wjKi0tRURERIMSA23cv38fYWFh8PLygqmpKWxtbREQEIBDhw41yfFeFs10HQBjjL0q4uLi8Pbbb8PExASTJk1Cp06dUFlZiZMnTyIsLAwZGRnYunVrvfaZmpqKpUuXYvLkybCxsWmawJ+6dOkSli5dCj8/P7Ru3Vqrbb799lsEBwfD0dER7777Ltq1a4eSkhIkJCRg6tSpyM3NxcKFC5s07mdVWlqKpUuXAgD8/Pwadd9Xr17FgAEDcPfuXbz33nvo1q0bCgsLsWPHDgwfPhwff/wxVq1apdW+fH19UVZWBpFIVO843N3dUVZWBmNj43pvqyucwDDG2HOQlZWFCRMmwN3dHYmJiXB2dhbqQkJCkJmZibi4OB1G2Ph+/fVXBAcHQyKR4PDhw7CyshLq5syZg9OnT+PixYs6jFC3qqqqMHbsWDx8+BAnTpxAz549hbq5c+finXfewZdffolu3bph/PjxavdTXl4OkUgEQ0NDmJqaNigWAwODBm+rM8QYY6zJBQcHEwD65Zdf6myblZVFACg6OrpWHQBasmQJEREtWbKEANR6ZWVlERFRVVUVLVu2jDw8PEgkEpG7uzuFh4dTeXm52n3Kc3d3p6CgICIiio6OVnmspKQktecxePBgatasGd26davOc1YXx9mzZ2nw4MFkZWVFFhYW1L9/f0pLS1NoU1lZSREREeTp6UkmJiZka2tLffr0oWPHjim0u3z5Mo0ZM4aaN29OJiYm5OPjQwcOHNAYk+xnofySjzMhIYH69u1L5ubmZG1tTW+99RZdunSpzvPduXMnAaBly5aprC8sLCQbGxtq3769UJaUlEQAaOfOnbRo0SJycXEhAwMDevjwoVCn/DPZsGEDtWnThkxNTal79+504sQJ6tevH/Xr16/Wecr/zgUFBZGFhQX98ccfNGLECLKwsCA7OzuaN28ePXnypM7za2rcA8MYY8/Bjz/+CA8PD/Tu3bvR9jl69Ghcu3YNO3fuxJo1a2BnZwcAsLe3BwBMmzYN27dvx9ixYzFv3jz873//Q2RkJC5fvoz9+/fX61i+vr748MMPsX79eixcuBAdOnQAAOGrstLSUiQkJMDX1xdubm4NOr+MjAy88cYbEIvFmD9/PoyNjbFlyxb4+fkhJSVF6LGIiIhAZGQkpk2bhh49eqC4uBinT5/G2bNnMWjQIGFfffr0QcuWLfHJJ5/AwsICe/bswciRI/Hf//4Xo0aNUhmDvb09oqKiMHPmTIwaNQqjR48GAHTp0gUAcPz4cQwZMgQeHh6IiIhAWVkZvv76a/Tp0wdnz57VeKvtxx9/BABMmjRJZb21tTVGjBiB7du3IzMzE56enkLdZ599BpFIhI8//hgVFRVqbxtFRUVh1qxZeOONNzB37lxkZ2dj5MiRaN68OVxdXTVc/RrV1dUICAhAz5498eWXX+L48eP46quv0LZtW8ycObPO7ZuUrjMoxhh72RUVFREAGjFihFbtte2BISJatWqVQq+LTHp6OgGgadOmKZR//PHHBIASExPV7lNGvgeGiCg2NrbOXheZ33//nQDQRx99VGdbdXGMHDmSRCIR3bhxQyi7c+cOWVlZka+vr1D22muvUWBgoMZ9DxgwgDp37qzQ+ySVSql3797Url07jdvevXtX7TXq2rUrOTg40P3794Wy33//nQwNDWnSpEka99u1a1eytrbW2Gb16tUEgA4ePEhEf/XAeHh4UGlpqUJb5R6YiooKatGiBXXv3p2qqqqEdtu2bSMAWvXAQEUP0d///nfy8fHRGPfzwLOQGGOsiRUXFwOAwhiQpnb48GEAQGhoqEL5vHnzAKDJx9s86zlXV1fj2LFjGDlyJDw8PIRyZ2dnTJw4ESdPnhSOYWNjg4yMDFy/fl3lvh48eIDExESMGzcOJSUluHfvHu7du4f79+8jICAA169fx59//lnvGHNzc5Geno7JkyfD1tZWKO/SpQsGDRok/AzUKSkpqfP6yOpl5yoTFBQEMzMzjduePn0a9+/fx/Tp09Gs2V83XN555x00b95c47bygoODFd6/8cYbuHnzptbbNxVOYBhjrImJxWIANR9Yz8utW7dgaGiocNsBAJycnGBjY4Nbt2416fGf9Zzv3r2L0tJSeHl51arr0KEDpFIpbt++DQBYtmwZCgsL8be//Q2dO3dGWFgYzp8/L7TPzMwEEeFf//oX7O3tFV5LliwBABQUFNQ7Rtk1VBfjvXv38PjxY7XbW1lZ1Xl9ZPXKiU6bNm20jk/5d6BZs2ZazyIzNTUVbknKNG/eHA8fPtRq+6bEY2AYY6yJicViuLi4aD3jxsDAQGV5Q9ZMUbcvbTzLGi2enp5o1qwZLly40OB9aMvX1xc3btzAgQMHcOzYMXz77bdYs2YNNm/ejGnTpkEqlQIAPv74YwQEBKiN93nr0KED0tPTkZOTo3ackCwR8/b2Viivq/elsRgZGT2X4zQE98AwxthzMGzYMNy4cQNpaWl1tpV17ysvTqeq10RdguLu7g6pVFrrtkp+fj4KCwvh7u6ucDzlY1VWViI3N1erY6libm6O/v3748SJE0JPSX3Y29vD3NwcV69erVV35coVGBoaolWrVkKZra0t3nvvPezcuRO3b99Gly5dhFV9ZbegjI2NMXDgQJUvTbdyNF1jAGpjtLOzg4WFhdr9Dhs2DADw/fffq6wvLi7GgQMH0L59+wYlWLL4MjMzFcqfPHlS78UIX0ScwDDG2HMwf/58WFhYYNq0acjPz69Vf+PGDaxbtw5ATY+NnZ0dTpw4odBm06ZNtbaTfUAqJyBDhw4FAKxdu1ahfPXq1QCAwMBAoaxt27a1jrV169ZaPTDqjqXOkiVLQER499138ejRo1r1Z86cwfbt21Vua2RkBH9/fxw4cEDhwzY/Px8xMTHo27evcJvq/v37CttaWlrC09MTFRUVAAAHBwf4+flhy5YttZIyoOZ2lSbm5uYAap+3s7Mzunbtiu3btyvUXbx4EceOHRN+BuqMHTsW3t7eWLFiBU6fPq1QJ5VKMXPmTDx8+FC4zVVf3bp1Q4sWLfDNN9/gyZMnQvmOHTteiFtAz4pvITHG2HPQtm1bxMTEYPz48ejQoYPCSrypqamIjY3F5MmThfbTpk3DihUrMG3aNHTr1g0nTpzAtWvXau3Xx8cHALBo0SJMmDABxsbGGD58OF577TUEBQVh69atKCwsRL9+/fDbb79h+/btGDlyJN58802FYwUHB2PMmDEYNGgQfv/9dxw9elSYli3TtWtXGBkZ4d///jeKiopgYmKC/v37w8HBQeU59+7dGxs3bsQHH3yA9u3bK6zEm5ycjIMHD2L58uVqr9ny5csRHx+Pvn374oMPPkCzZs2wZcsWVFRUYOXKlUI7b29v+Pn5wcfHB7a2tjh9+jT27t2LWbNmCW02btyIvn37onPnzpg+fTo8PDyQn5+PtLQ0/PHHH/j999/VxmFmZgZvb2/s3r0bf/vb32Bra4tOnTqhU6dOWLVqFYYMGQKJRIKpU6cK06itra3rfK6TSCTC3r17MWDAAPTt21dhJd6YmBicPXsW8+bNw4QJEzTuR9P+IyIiMHv2bPTv3x/jxo1DdnY2tm3bhrZt2z7T7cUXgq6nQTHG2Kvk2rVrNH36dGrdujWJRCKysrKiPn360Ndff60wxbe0tJSmTp1K1tbWZGVlRePGjaOCggKV03k/++wzatmyJRkaGtZayG7p0qXUpk0bMjY2platWqlcyK66upoWLFhAdnZ2ZG5uTgEBAZSZmVlrGjUR0TfffEMeHh5kZGSk9ZTqM2fO0MSJE8nFxYWMjY2pefPmNGDAANq+fTtVV1cL7VSd29mzZykgIIAsLS3J3Nyc3nzzTUpNTVVos3z5curRowfZ2NiQmZkZtW/fnj7//HOqrKxUaHfjxg2aNGkSOTk5kbGxMbVs2ZKGDRtGe/furfMcUlNTycfHh0QiUa04jx8/Tn369CEzMzMSi8U0fPhwrRaykykoKKDQ0FBhIT4bGxsaOHCgMHVanmyqdGxsrNo65Z/J+vXryd3dnUxMTKhHjx70yy+/kI+PDw0ePFhoo2khO2WyBRR1zYCISGfZE2OMMcaeK6lUCnt7e4wePRrffPONrsNpMB4DwxhjjL2kysvLodxP8f333+PBgweN/mDK5417YBhjjLGXVHJyMubOnYu3334bLVq0wNmzZ/Hdd9+hQ4cOOHPmTIOeXP2i4EG8jDHG2EuqdevWaNWqFdavX48HDx7A1tYWkyZNwooVK/Q6eQG4B4YxxhhjeojHwDDGGGNM73ACwxhjjDG9w2NgGGPsKalUijt37sDKykr/F/liTE8REUpKSuDi4gJDQ/X9LJzAMMbYU3fu3FF4vg5jTHdu374NV1dXtfWcwDDG2FOyB/qZAuD+F8Z0gwCUAxofsAlwAsMYYwLZbSMDcALDmK7VdRuXB/EyxhhjTO9wAsMYY4wxvcMJDGOMMcb0DicwjDHGGNM7nMAwxhhjTO9wAsMYY4wxvcMJDGOMMcb0DicwjDHGGNM7nMAwxhhjTO9wAsMYY4wxvcMJDGOMMcb0DicwOpKcnAwDAwPs3bu3SY/TunVrTJ48udH2FxERUefzKZpKdnY2DAwMsG3btkbdb2NfI8YYY03vlUxgtm3bBgMDAxgYGODkyZO16okIrVq1goGBAYYNG6aDCJ+/R48eYcmSJejUqRMsLCzQokULdO3aFR999BHu3Lmj6/CeWWpqKiIiIlBYWKjrUJrMpk2bGj25UycmJgZr1659LsdijDFVXskERsbU1BQxMTG1ylNSUvDHH3/AxMREB1E9f1VVVfD19cWqVavwxhtvYPXq1Vi4cCFef/11xMTE4Nq1a0LbxYsXo6ysTIfRNkxqaiqWLl2qMoG5evUqvvnmm+cfVCPjBIYx9ipppusAdGno0KGIjY3F+vXr0azZX5ciJiYGPj4+uHfvng6je35++OEHnDt3Djt27MDEiRMV6srLy1FZWSm8b9asmcK1ehm8KokqY4y9TF7pHph//OMfuH//PuLj44WyyspK7N27t9YHucyXX36J3r17o0WLFjAzM4OPj4/KcSzx8fHo27cvbGxsYGlpCS8vLyxcuFBjPBUVFRg2bBisra2RmpoKAJBKpVi7di06duwIU1NTODo6YsaMGXj48KHCtkSE5cuXw9XVFebm5njzzTeRkZGh1XW4ceMGAKBPnz616kxNTSEWi4X3qsbAGBgYYNasWYiNjYW3tzfMzMwgkUhw4cIFAMCWLVvg6ekJU1NT+Pn5ITs7W2F7dWNQ/Pz84OfnpzH28+fPY/LkyfDw8ICpqSmcnJwwZcoU3L9/XyHmsLAwAECbNm2E24eyOFQd/+bNm3j77bdha2sLc3Nz9OrVC3FxcQptZOOY9uzZg88//xyurq4wNTXFgAEDkJmZqTFumT///BNTp06Fi4sLTExM0KZNG8ycOVNIGtWNOZLdBpU/h4yMDKSkpAjnJ3/ttDkf5X0qn2dycjKAmp9LXFwcbt26JRyrdevWWp2vtlasWAEDAwPMmTNHKCsvL0dISAhatGgBS0tLjBkzBvn5+Qrb5eTkIDAwEObm5nBwcEBYWBiePHnSqLExxl4ML9ef0vXUunVrSCQS7Ny5E0OGDAEA/PTTTygqKsKECROwfv36WtusW7cOb731Ft555x1UVlZi165dePvtt3Ho0CEEBgYCADIyMjBs2DB06dIFy5Ytg4mJCTIzM/HLL7+ojaWsrAwjRozA6dOncfz4cXTv3h0AMGPGDGzbtg3vvfcePvzwQ2RlZWHDhg04d+4cfvnlFxgbGwMAPv30UyxfvhxDhw7F0KFDcfbsWfj7+yv0nqjj7u4OAPj++++xePHiBg3S/fnnn3Hw4EGEhIQAACIjIzFs2DDMnz8fmzZtwgcffICHDx9i5cqVmDJlChITE+t9DFXi4+Nx8+ZNvPfee3ByckJGRga2bt2KjIwM/PrrrzAwMMDo0aNx7do17Ny5E2vWrIGdnR0AwN7eXuU+8/Pz0bt3b5SWluLDDz9EixYtsH37drz11lvYu3cvRo0apdB+xYoVMDQ0xMcff4yioiKsXLkS77zzDv73v/9pjP3OnTvo0aMHCgsL8f7776N9+/b4888/sXfvXpSWlkIkEml9HdauXYvZs2fD0tISixYtAgA4Ojo26HzqsmjRIhQVFeGPP/7AmjVrAACWlpb12ocmp06dwpYtW9ClSxeF8rlz5yIuLg6xsbGwtrbGrFmzMHr0aOHfVXV1NQIDA+Hk5ITU1FTk5uZi0qRJMDY2xhdffNFo8THGXhD0CoqOjiYAdOrUKdqwYQNZWVlRaWkpERG9/fbb9OabbxIRkbu7OwUGBipsK2snU1lZSZ06daL+/fsLZWvWrCEAdPfuXbUxJCUlEQCKjY2lkpIS6tevH9nZ2dG5c+eENj///DMBoB07dihse+TIEYXygoICEolEFBgYSFKpVGi3cOFCAkBBQUEar0dpaSl5eXkRAHJ3d6fJkyfTd999R/n5+bXaLlmyhJR/bQCQiYkJZWVlCWVbtmwhAOTk5ETFxcVCeXh4OAFQaOvu7q4yxn79+lG/fv2E91lZWQSAoqOjFWJXtnPnTgJAJ06cEMpWrVpV67jqjj9nzhwCQD///LNQVlJSQm3atKHWrVtTdXU1Ef31M+zQoQNVVFQIbdetW0cA6MKFC7WOJW/SpElkaGhIp06dqlUn+zmqut5Ef/0Oy59Px44dFa5Xfc9H1T7lzzMpKUkoCwwMJHd3d43n1xAlJSXUrl07io+Pp379+tFHH31ERESFhYVkbGxMsbGxQtvLly8TAEpLSyMiosOHD5OhoSHl5eUJbaKiokgsFiv8fDQpKioiAGQGkDm/+MUvnbzMAAJARUVFGv+9vtK3kABg3LhxKCsrw6FDh1BSUoJDhw6pvX0EAGZmZsL3Dx8+RFFREd544w2cPXtWKLexsQEAHDhwAFKpVOPxi4qK4O/vjytXriA5ORldu3YV6mR/aQ4aNAj37t0TXj4+PrC0tERSUhIA4Pjx46isrMTs2bMVek/ku981MTMzw//+9z/hNsu2bdswdepUODs7Y/bs2aioqKhzHwMGDFC4jdCzZ08AwJgxY2BlZVWr/ObNm1rFpk3sMuXl5bh37x569eoFAAo/k/o4fPgwevTogb59+wpllpaWeP/995GdnY1Lly4ptH/vvfcUekveeOMNAJrPUSqV4ocffsDw4cPRrVu3WvWNOVW9vuejSyEhIQgMDMTAgQMVys+cOYOqqiqF8vbt28PNzQ1paWkAgLS0NHTu3FnoeQKAgIAAFBcXq72dWlFRgeLiYoUXY0w/vPIJjL29PQYOHIiYmBjs27cP1dXVGDt2rNr2hw4dQq9evWBqagpbW1vY29sjKioKRUVFQpvx48ejT58+mDZtGhwdHTFhwgTs2bNHZTIzZ84cnDp1CsePH0fHjh0V6q5fv46ioiI4ODjA3t5e4fXo0SMUFBQAAG7dugUAaNeuXa1za968uVbXwdraGitXrkR2djays7Px3XffwcvLCxs2bMBnn31W5/Zubm619gcArVq1UlmuPIanoR48eICPPvoIjo6OMDMzg729Pdq0aQMACj+T+rh16xa8vLxqlXfo0EGol6d87rJrrukc7969i+LiYnTq1KlBMdZHfc9HV3bt2oWzZ88iMjKyVl1eXh5EIpHwx4GMo6Mj8vLyhDbyyYusXlanSmRkJKytrYWX8u8rY+zF9UqPgZGZOHEipk+fjry8PAwZMqTWf5IyP//8M9566y34+vpi06ZNcHZ2hrGxMaKjoxWmY5uZmeHEiRNISkpCXFwcjhw5gt27d6N///44duwYjIyMhLYjRozArl27sGLFCnz//fcwNPwrp5RKpXBwcMCOHTtUxqNuDMezcnd3x5QpUzBq1Ch4eHhgx44dWL58ucZt5M9Jm3IiEr5X19tQXV2tdnuZcePGITU1FWFhYejatSssLS0hlUoxePDgOnu/Gos259hQmq5NY3uex1J2+/ZtfPTRR4iPj4epqWmTH08mPDwcoaGhwvvi4mJOYhjTE5zAABg1ahRmzJiBX3/9Fbt371bb7r///S9MTU1x9OhRham30dHRtdoaGhpiwIABGDBgAFavXo0vvvgCixYtQlJSkkI3+MiRI+Hv74/JkyfDysoKUVFRQl3btm1x/Phx9OnTR+FWiTLZINzr16/Dw8NDKL979+4z9XQ0b94cbdu2xcWLFxu8D22Po2p9llu3bimcj7KHDx8iISEBS5cuxaeffiqUX79+vVbb+tyScXd3x9WrV2uVX7lyRah/Vvb29hCLxXVeW1lvTmFhoUJirarXRN05ans+8seSV59jNdSZM2dQUFCA119/XSirrq7GiRMnsGHDBhw9ehSVlZW1rkN+fj6cnJwAAE5OTvjtt98U9iubpSRro8zExISn0TOmp175W0hAzXiAqKgoREREYPjw4WrbGRkZwcDAQOEv0uzsbPzwww8K7R48eFBrW9nYFlXjSSZNmoT169dj8+bNWLBggVA+btw4VFdXq7yF8+TJE+GDZuDAgTA2NsbXX3+t8Fe/tguN/f777yrXvLl16xYuXbqk8vZDY2rbti1+/fVXhRlThw4dwu3btzVuJ+v5UO7pUHXeFhYWAGp/OKsydOhQ/Pbbb8LYCgB4/Pgxtm7ditatW8Pb27vOfdTF0NAQI0eOxI8//ojTp0/XqpedU9u2bQEAJ06cUIhl+/bttbaxsLBQeX7ano+qY1VXV2Pr1q0qj9XQW3SqDBgwABcuXEB6errw6tatG9555x3he2NjYyQkJAjbXL16FTk5OZBIJAAgTN2X3VoFamapicXiRvmZMcZeLNwD81RQUFCdbQIDA7F69WoMHjwYEydOREFBATZu3AhPT0+cP39eaLds2TKcOHECgYGBcHd3R0FBATZt2gRXV1eFgZTyZs2aheLiYixatAjW1tZYuHAh+vXrhxkzZiAyMhLp6enw9/eHsbExrl+/jtjYWKxbtw5jx46Fvb09Pv74Y2Hq8tChQ3Hu3Dn89NNPwpRhTeLj47FkyRK89dZb6NWrFywtLXHz5k385z//QUVFBSIiIrS+jg0xbdo07N27F4MHD8a4ceNw48YN/N///Z/wgaqOWCyGr68vVq5ciaqqKrRs2RLHjh1DVlZWrbY+Pj4AaqYAT5gwAcbGxhg+fLiQ2Mj75JNPhKn1H374IWxtbbF9+3ZkZWXhv//9r8JtvmfxxRdf4NixY+jXrx/ef/99dOjQAbm5uYiNjcXJkydhY2MDf39/uLm5YerUqQgLC4ORkRH+85//wN7eHjk5ObXOMSoqCsuXL4enpyccHBzQv39/rc+nY8eO6NWrF8LDw/HgwQPY2tpi165dKtdR8fHxwe7duxEaGoru3bvD0tJSY/JfFysrq1rjgWSPtJCVT506FaGhobC1tYVYLMbs2bMhkUiEQdv+/v7w9vbGu+++i5UrVyIvLw+LFy9GSEgI97Iw9jLSfoLjy0N+GrUmqqZRf/fdd9SuXTsyMTGh9u3bU3R0dK2prgkJCTRixAhycXEhkUhELi4u9I9//IOuXbsmtJGfRi1v/vz5BIA2bNgglG3dupV8fHzIzMyMrKysqHPnzjR//ny6c+eO0Ka6upqWLl1Kzs7OZGZmRn5+fnTx4kW1U5Tl3bx5kz799FPq1asXOTg4ULNmzcje3p4CAwMpMTFRoa26adQhISEKZbIpz6tWrVIoV3feX331FbVs2ZJMTEyoT58+dPr0aa2mUf/xxx80atQosrGxIWtra3r77bfpzp07BICWLFmicIzPPvuMWrZsSYaGhgrThVVdoxs3btDYsWPJxsaGTE1NqUePHnTo0CGtzkVVnOrcunWLJk2aRPb29mRiYkIeHh4UEhKiMO33zJkz1LNnTxKJROTm5karV69WOeU5Ly+PAgMDycrKigAoXDttzkfWbuDAgWRiYkKOjo60cOFCio+PrzWN+tGjRzRx4kSysbERpt83Nvlp1EREZWVl9MEHH1Dz5s3J3NycRo0aRbm5uQrbZGdn05AhQ8jMzIzs7Oxo3rx5VFVVpfUxeRo1v/il+5e206gNiBphpCFjjL0EiouLYW1tDTMAunnmOmOMAJShZiap/ErwyngMDGOMMcb0DicwjDHGGNM7nMAwxhhjTO9wAsMYY4wxvcMJDGOMMcb0DicwjDHGGNM7L+1CdlKpFHfu3IGVlVWjL3vOGKsbEaGkpAQuLi6NtvgfY4zJvLQJzJ07d/ihbIy9AG7fvg1XV1ddh8EYe8m8tAmMlZUVAMAUvCAVY7pAAMrx179FxhhrTC9tAiO7bWQATmAY0yW+hcsYawovbQKjj4xQM6ra6OnLGDU9SKYAzAFYADB5+tX4aRtAcSS2tI5jVKsoU7WNqnayGNXVabsPdcfUZjtt41duK1VRXq1Up1wuq1O1H233oeq4ym3ras8YY6y2eiUwUVFRiIqKQnZ2NoCap9d++umnGDJkCADAz88PKSkpCtvMmDEDmzdvFt7n5ORg5syZSEpKgqWlJYKCghAZGYlmzf4KJTk5GaGhocjIyECrVq2wePFiTJ48uYGnqD+qn76qdB0IY4wx9oKrVwLj6uqKFStWoF27diAibN++HSNGjMC5c+fQsWNHAMD06dOxbNkyYRtzc3Ph++rqagQGBsLJyQmpqanIzc3FpEmTYGxsjC+++AIAkJWVhcDAQAQHB2PHjh1ISEjAtGnT4OzsjICAgMY453qT7+lQ1TMihmIPiQh/9YoYQTX53hZjua/GcnXKVP3lrvwXu/xf8rL3UqWvUHqvqs2z1Fcqxaock/L31VB9bowxxpg6z/w0altbW6xatQpTp06Fn58funbtirVr16ps+9NPP2HYsGG4c+cOHB0dAQCbN2/GggULcPfuXYhEIixYsABxcXG4ePGisN2ECRNQWFiII0eOaB1XYz9VVjmJMUVNsiF/W8ccNcmLqkTESM1+lMtQz+3UbWOkRVvlurraKseg/F7d8VUla4b4K9FT9V5WZqBq58qNlA8qf8GUL5omytmTpsyvUq68CiBpzdvyp1VVcq/yp68qpTpZmbpDlAN4DOABgDwAdwGUPC1XlTyqIp8Yyo73uI5tGou2T5R9kfDTqBnTPW3/72jwGJjq6mrExsbi8ePHkEgkQvmOHTvwf//3f3BycsLw4cPxr3/9S+iFSUtLQ+fOnYXkBQACAgIwc+ZMZGRk4O9//zvS0tIwcOBAhWMFBARgzpw5GuOpqKhARUWF8L64uLihp6aS/IeL7MMHqPlQYU1IiroH9jDGGHvl1DuBuXDhAiQSCcrLy2FpaYn9+/fD29sbADBx4kS4u7vDxcUF58+fx4IFC3D16lXs27cPAJCXl6eQvAAQ3ufl5WlsU1xcjLKyMpiZmamMKzIyEkuXLq3v6TDGGGNMD9U7gfHy8kJ6ejqKioqwd+9eBAUFISUlBd7e3nj//feFdp07d4azszMGDBiAGzduoG3bto0auLLw8HCEhoYK74uLi1/oheyMoXi7yRSAFQD7py+np18dn5abPt1OdvdC/tZEBRSpumMiP6ZGuU75bos27ZqCqlk5gHYziOq7nXx9XTOK1I3nkS9TNUZI+faQtnXajD1SPjZUfK987qrOjTHG9FW9ExiRSARPT08AgI+PD06dOoV169Zhy5Yttdr27NkTAJCZmYm2bdvCyckJv/32m0Kb/Px8AICTk5PwVVYm30YsFqvtfQEAExMTmJiY1Pd0dEY2DkJGlhxchfohHjKapuOqommsjHxZfcbLyL6vaxwOoH7MjPL3qqaFK8cpT1WypS4B0zahU5WkGcp9NVZRL6NuCrS6KdKaEqbGGGytinwCVQqgGDUJsPLAa8YYe9E98zowUqlUYeyJvPT0dACAs7MzAEAikeDzzz9HQUEBHBwcAADx8fEQi8XCbSiJRILDhw8r7Cc+Pl5hnM3LQt26L1ZPXzao6YWRvZcfJCzbXhNVM5ka8kFe136qVZTJl2vbXpW6PkzlP6gNof6Du679abO+jKa1WtQlH8plsu+NUXsArjbx12c4kKpzki+T/b7JevUYY0yf1CuBCQ8Px5AhQ+Dm5oaSkhLExMQgOTkZR48exY0bNxATE4OhQ4eiRYsWOH/+PObOnQtfX1906dIFAODv7w9vb2+8++67WLlyJfLy8rB48WKEhIQIvSfBwcHYsGED5s+fjylTpiAxMRF79uxBXFxc45+9jqlb9yWvCY6laqaTcrmmNtqUqet90VSmzX6Vv29Iz0tDenVU1atrp6w+C/Vpu8ie/Hbqji+7flVq2hg/3afs5yHrCZSdJ4+XZozpi3olMAUFBZg0aRJyc3NhbW2NLl264OjRoxg0aBBu376N48ePY+3atXj8+DFatWqFMWPGYPHixcL2RkZGOHToEGbOnAmJRAILCwsEBQUprBvTpk0bxMXFYe7cuVi3bh1cXV3x7bff6mwNmPrSplfFGkAL1PSoyNaTUbf2S123N5TV9cHa0NnEqurUjTeRr1O3L23Goqg7dl1jOjT1gqi6DQOl9+pu1ajbj6pyqNlOU3zK58EYY0y9Z14H5kXF6zkwmbrWvdE0Rqeunib5r/J1yuXaqCupq6tXR5YYlaNmfIv8UjW6wOvAMMYaosnXgWFMX6i7VccYY0x/cQLzHCn/hS8/hdoUfz2kUfZSRflWhExDBpPK6uqa/SJfp6otY4wx9rxxAtPI1CUpstlDsjJNq+EDNQmC/LL7ykvyQ0O5/HtVbVTVK29X17Gg5j2U2stfF3WDc5Vvu2g7IFfTLZyGDs5Vpum2jjbjY9RNd66Se1+l9FV+rR/lMuX9ydYDegzF20ZQOqbsttJj1DyOQDlBZYwxfcMJTCOT78GQf+QAY4wxxhoPJzAvAPneDuWVeVsAsEXNejCy723w1wwmWS+NuunE9e2tUNfLUZ+F3+Rp+gtfU52qAaua1mrRdn0XbW+71bXyrareFUCxl0Sb3hf5OuXVeeuq07Sar6ZzUHU9ZL00yg+ZZIyxF1W9EpioqChERUUhOzsbANCxY0d8+umnGDJkiEI7IsLQoUNx5MgR7N+/HyNHjhTqcnJyMHPmTCQlJcHS0hJBQUGIjIxEs2Z/hZKcnIzQ0FBkZGSgVatWWLx4MSZPntzgk2wqyh/u8o8GkL9tpO5hyOqmC8vfrilHzQMjCwHcxF8Ji6Z9yVOVCKhKRjQlNprWjpFXn3Vb1B2rrnaq6jQdT5v9qdsnUL8kS5up4ZrKlY+lHJNs8TvZui0iKCYysv2pmiauinwvoapbUIwx9iKrVwLj6uqKFStWoF27diAibN++HSNGjMC5c+fQsWNHod3atWthYFB7EmJ1dTUCAwPh5OSE1NRU5ObmYtKkSTA2NsYXX3wBAMjKykJgYCCCg4OxY8cOJCQkYNq0aXB2dn5h1oKRX9/FFDW9IVYAWgLwAOAFoDMAbwAWbQC0Rk0Xig1Ud50Yqtip8mIy8m2Uy5UH2Kj6XlUWpWpurqY/19XN5a1W0VZ+yo+q7om6ji+/P9kntKpPZ/lPb/nBJMrdE1X4a2CJ8iAT+bryOspk7ysBVABUpdhE+WslahKDcqW6chWHqpDbtSxs2Y+sWu59FWoeAfDg6asE/CgAxtir55nXgbG1tcWqVaswdepUADWPDxg2bBhOnz4NZ2dnhR6Yn376CcOGDcOdO3eEJ05v3rwZCxYswN27dyESibBgwQLExcXh4sWLwjEmTJiAwsJCHDlyROu4eD0H1eoazKtNvXJOVJ9tlb9Xlccpb6vuPBqirp4qTb0o8t9rmuWl6plHyvuqUrFdfXpNSlHTK1eCvxIh5Vh1jdeBYYw1RJOvA1NdXY3Y2Fg8fvxYeE5RaWkpJk6ciI0bNwoPZ5SXlpaGzp07C8kLAAQEBGDmzJnIyMjA3//+d6SlpWHgwIEK2wUEBGDOnDka46moqFB4JlNxcXFDT+2lJj9+gjHGGNNXda08X8uFCxdgaWkJExMTBAcHY//+/cKDGOfOnYvevXtjxIgRKrfNy8tTSF4ACO/z8vI0tikuLkZZWZnauCIjI2FtbS28WrVqVd9TY4wxxpieqHcPjJeXF9LT01FUVIS9e/ciKCgIKSkpyMzMRGJiIs6dO9cUcdYpPDwcoaGhwvvi4uIXNolRdUtG1fOSxE/fy4bMKC95L6M8wFXV7ZW6Bq3W5wGKyup7O6eht3/kqbuto6lO+faQcjt1i/upq9c0O0lVuaphOXXNbFLeDqg93kXdLCrla6DpOjHGmL6pdwIjEong6ekJAPDx8cGpU6ewbt06mJmZ4caNG7CxsVFoP2bMGLzxxhtITk6Gk5MTfvvtN4X6/Px8ABBuOTk5OQll8m3EYjHMzMzUxmViYiI80fpFp+42TlM8hVpbzzI2RqTltqIG1qkbF1PXzCUZbR5wKZ/4qVsFWZuZXnUlC3XNQlI1nkY5oZH97iiPw1EeV6Mqfin+WsxONn5Gm7E3jDH2onnmdWCkUikqKiqwdOlSTJs2TaGuc+fOWLNmDYYPHw4AkEgk+Pzzz1FQUAAHBwcAQHx8PMRisXAbSiKR4PDhwwr7iY+PF8bZsKbBY2OYLkVGRmLfvn24cuUKzMzM0Lt3b/z73/+Gl5eX0Ka8vBzz5s3Drl27UFFRgYCAAGzatEnhlrM2yzQwxl4O9fpXHR4ejiFDhsDNzQ0lJSWIiYlBcnIyjh49CicnJ5UDd93c3NCmTRsAgL+/P7y9vfHuu+9i5cqVyMvLw+LFixESEiL0ngQHB2PDhg2YP38+pkyZgsTEROzZswdxcXGNcLqNS36msjFqnmVkhZrF5uSnVHugZiZ1CxPU3B+S3RdSni6t6vkD8t0HUhXvgQaMZILm+yGyenV1yn+ya7qfoaqtfKakoQ1J1d+Oqeu2i6YZ13XVqVrmv77l6h4BoFyvajE65UcGKFNuK5um/SLORNJWSkoKQkJC0L17dzx58gQLFy6Ev78/Ll26BAsLCwA1Y+zi4uIQGxsLa2trzJo1C6NHj8Yvv/wCAFot08AYe3nUaxr11KlTkZCQgNzcXFhbW6NLly5YsGABBg0apHrnBga1FrK7desWZs6cieTkZFhYWCAoKAgrVqyotZDd3LlzcenSJbi6uuJf//pXvReye5mmQ6paUE5Vmbp6Ve+Vv69r+7r2pTzluSHjcBqy2Fxd22iifA3rOpYq6hIM+br6jJ1Rlc+pO678dOpC/LWmjLq4nrdnmUZ99+5dODg4ICUlBb6+vigqKoK9vT1iYmIwduxYAMCVK1fQoUMHpKWloVevXlot01CXl+n/Dcb0VZNMo/7uu+/qF4SK3Mjd3b3WLSJlfn5+OhsMXB/qBuPKFreTfZWtMyfbRp1qpXp1H0LafGjKvq/rw1RWVq2mTPl7VR/A9WnPmDaKiooA1KwzBQBnzpxBVVWVwhIL7du3h5ubm5DAaLNMgzJefoEx/cU3hp+R8mBJ+b/mZR/wqh4poK7noFqLNsqPE9D0dGjl96pi0NQTU1e9Nj07ymXyGtLrIt9W+a6aJuoGtirXa0rWlGclaXtrS9UMJFW3tJRnHCnHKmtTAsWBuC9Sz8uzkkqlmDNnDvr06YNOnToBqFleQSQS1Zok4OjoWOcSDLI6VSIjI7F06dJGPgPG2PPACcwzUJ4BAtTM8GCMNVxISAguXryIkydPNvmx9Gn5BcaYIk5gGGMvjFmzZuHQoUM4ceIEXF1dhXInJydUVlaisLBQoRcmPz9fYQmGupZpUKZPyy8wxhQ1ZP4KY4w1KiLCrFmzsH//fiQmJgozF2V8fHxgbGyMhIQEoezq1avIyckRlliQSCS4cOECCgoKhDbKyzQwxl4e3APDGNO5kJAQxMTE4MCBA7CyshLGrFhbW8PMzAzW1taYOnUqQkNDYWtrC7FYjNmzZ0MikaBXr14AtFumgTH28qhXD0xUVBS6dOkCsVgMsVgMiUSCn376SaifMWMG2rZtCzMzM9jb22PEiBG4cuWKwj5ycnIQGBgIc3NzODg4ICwsDE+ePFFok5ycjNdffx0mJibw9PTEtm3bGn6GjLEXXlRUFIqKiuDn5wdnZ2fhtXv3bqHNmjVrMGzYMIwZMwa+vr5wcnLCvn37hHojIyMcOnQIRkZGkEgk+Oc//4lJkyZh2bJlujglxlgTq9c6MD/++COMjIzQrl07EBG2b9+OVatW4dy5c+jYsSO2bt0qTG188OABIiIikJ6ejqysLBgZGaG6uhpdu3aFk5MTVq1aJSw0NX36dGGhqaysLHTq1AnBwcGYNm0aEhISMGfOHMTFxSEgIEDrE+P1HBjTrWdZB0ZX+P8NxnRP2/876pXAqGJra4tVq1Zh6tSpterOnz+P1157DZmZmWjbtq1WC00tWLAAcXFxuHjxorCfCRMmoLCwEEeOHNE6Lv6PiDHd4gSGMdYQ2v7f0eBBvNXV1di1axceP36s8jlFjx8/RnR0NNq0aSNMS1S30FRxcTEyMjKENvKLVcnapKWlaYynoqICxcXFwku2EBbxi1/80tkLgMoFLRlj7FnVexDvhQsXIJFIUF5eDktLS+zfv19hhP+mTZswf/58PH78GF5eXoiPjxeW8NZmoSl1bYqLi1FWVqb2idTqFqQqr+8JMsYaVUlJCaytrXUdBmPsJVPvBMbLywvp6ekoKirC3r17ERQUhJSUFCGJeeeddzBo0CDk5ubiyy+/xLhx4/DLL7/A1NS00YOXp7wgVWFhIdzd3ZGTk8P/eTaAbEGv27dv6033/4vmVb+GRISSkhK4uLjoOhTG2Euo3gmMSCSCp6cngJq1GU6dOoV169Zhy5YtAGqmPVpbW6Ndu3bo1asXmjdvjv379+Mf//iHVgtNOTk5CWXybcRisdreF0D9glTW1tav5IdHY5HNOGMN9ypfQ/7jgTHWVJ55ITupVKrwMDR5RAQiEuq1WWhKIpEoLFYla6NqnA1jjDHGXk316oEJDw/HkCFD4ObmhpKSEsTExCA5ORlHjx7FzZs3sXv3bvj7+8Pe3h5//PEHVqxYATMzMwwdOhSAdgtNBQcHY8OGDZg/fz6mTJmCxMRE7NmzB3FxcY1/9owxxhjTS/VKYAoKCjBp0iTk5ubC2toaXbp0wdGjRzFo0CDcuXMHP//8M9auXYuHDx/C0dERvr6+SE1NhYODA4C/FpqaOXMmJBIJLCwsEBQUpLDQVJs2bRAXF4e5c+di3bp1cHV1xbfffluvNWCAmltKS5Ys4RU4G4iv37Pja8gYY03nmdeBYYyxlwWvA8OY7hGaeB0YxhhjjDFd4QSGMcYYY3qHExjGGGOM6R1OYBhjjDGmdziBYYwxxpjeeWETmMjISHTv3h1WVlZwcHDAyJEjcfXqVYU25eXlCAkJQYsWLWBpaYkxY8bUWsU3JycHgYGBMDc3h4ODA8LCwvDkyROFNsnJyXj99ddhYmICT09PbNu2ralP77nQ5hr6+fnBwMBA4RUcHKzQ5lW9hlFRUejSpYuwkq5EIsFPP/0k1PPvH2OM6c4Lm8CkpKQgJCQEv/76K+Lj41FVVQV/f388fvxYaDN37lz8+OOPiI2NRUpKCu7cuYPRo0cL9dXV1QgMDERlZSVSU1Oxfft2bNu2DZ9++qnQJisrC4GBgXjzzTeRnp6OOXPmYNq0aTh69OhzPd+moM01BIDp06cjNzdXeK1cuVKoe5WvoaurK1asWIEzZ87g9OnT6N+/P0aMGCE8OZ1//xhjTIdITxQUFBAASklJISKiwsJCMjY2ptjYWKHN5cuXCQClpaUREdHhw4fJ0NCQ8vLyhDZRUVEkFoupoqKCiIjmz59PHTt2VDjW+PHjKSAgoKlP6blTvoZERP369aOPPvpI7TZ8DRU1b96cvv32W/79e0kVFRURADIDyJxf/OKXTl5mAAGgoqIijf9eX9geGGVFRUUAAFtbWwDAmTNnUFVVhYEDBwpt2rdvDzc3N6SlpQEA0tLS0LlzZzg6OgptAgICUFxcLPwVnZaWprAPWRvZPl4mytdQZseOHbCzs0OnTp0QHh6O0tJSoY6vYY3q6mrs2rULjx8/hkQi4d8/xhjTsXo/jVoXpFIp5syZgz59+qBTp04AgLy8PIhEItjY2Ci0dXR0RF5entBG/sNDVi+r09SmuLgYZWVlGp+ArU9UXUMAmDhxItzd3eHi4oLz589jwYIFuHr1Kvbt2weAr+GFCxcgkUhQXl4OS0tL7N+/H97e3khPT+ffP8YY0yG9SGBCQkJw8eJFnDx5Uteh6C111/D9998Xvu/cuTOcnZ0xYMAA3LhxA23btn3eYb5wvLy8kJ6ejqKiIuzduxdBQUFISUnRdViMMfbKe+FvIc2aNQuHDh1CUlISXF1dhXInJydUVlaisLBQoX1+fj6cnJyENsqzQmTv62ojFotfmr9+1V1DVXr27AkAyMzMBMDXUCQSwdPTEz4+PoiMjMRrr72GdevW8e8fY4zp2AubwBARZs2ahf379yMxMRFt2rRRqPfx8YGxsTESEhKEsqtXryInJwcSiQQAIJFIcOHCBRQUFAht4uPjIRaL4e3tLbSR34esjWwf+qyua6hKeno6AMDZ2RkAX0NlUqkUFRUV/PvHGGO69lyG9jfAzJkzydrampKTkyk3N1d4lZaWCm2Cg4PJzc2NEhMT6fTp0ySRSEgikQj1T548oU6dOpG/vz+lp6fTkSNHyN7ensLDw4U2N2/eJHNzcwoLC6PLly/Txo0bycjIiI4cOfJcz7cp1HUNMzMzadmyZXT69GnKysqiAwcOkIeHB/n6+gr7eJWv4SeffEIpKSmUlZVF58+fp08++YQMDAzo2LFjRMS/fy8jnoXEL37p/qXtLKQXNoHB0xNQfkVHRwttysrK6IMPPqDmzZuTubk5jRo1inJzcxX2k52dTUOGDCEzMzOys7OjefPmUVVVlUKbpKQk6tq1K4lEIvLw8FA4hj6r6xrm5OSQr68v2drakomJCXl6elJYWFitX5pX9RpOmTKF3N3dSSQSkb29PQ0YMEBIXoj49+9lxAkMv/il+5e2CYwBEdHz7/dhjLEXT3FxMaytrWEGwEDXwTD2iiIAZahZ+kMsFqtt98KOgWGMMcYYU4cTGMYYY4zpHU5gGGOMMaZ3OIFhjDHGmN7hBIYxxhhjeocTGMYYY4zpHU5gGGOMMaZ3OIFhjDHGmN7hBIYxxhhjeocTGMYYY4zpHU5gGGMvnY0bN6J169YwNTVFz5498dtvv+k6JMZYI+MEhjH2Utm9ezdCQ0OxZMkSnD17Fq+99hoCAgJQUFCg69AYY42IH+bIGHup9OzZE927d8eGDRsAAFKpFK1atcLs2bPxySefKLStqKhARUWF8L6oqAhubm4wBT/MkTFdIQDlAAoLC2Ftba22XbPnFhFjjDWxyspKnDlzBuHh4UKZoaEhBg4ciLS0tFrtIyMjsXTp0lrl5U0aJWNMGyUlJZzAMMZeDffu3UN1dTUcHR0Vyh0dHXHlypVa7cPDwxEaGiq8l0qlePDgAVq0aAEDg8btgykuLkarVq1w+/ZtiMXiRt13U+GYnw+OWRERoaSkBC4uLhrbcQLDGHtlmZiYwMTERKHMxsamSY8pFov15kNKhmN+Pjjmv2jqeZHhQbyMsZeGnZ0djIyMkJ+fr1Cen58PJycnHUXFGGsKnMAwxl4aIpEIPj4+SEhIEMqkUikSEhIgkUh0GBljrLHxLSTG2EslNDQUQUFB6NatG3r06IG1a9fi8ePHeO+993Qal4mJCZYsWVLrltWLjGN+PjjmhuFp1Iyxl86GDRuwatUq5OXloWvXrli/fj169uyp67AYY42IExjGGGOM6R0eA8MYY4wxvcMJDGOMMcb0DicwjDHGGNM7nMAwxhhjTO9wAsMYY1o6ceIEhg8fDhcXFxgYGOCHH36o1eby5ct46623YG1tDQsLC3Tv3h05OTlCfXl5OUJCQtCiRQtYWlpizJgxtRbey8nJQWBgIMzNzeHg4ICwsDA8efKkSWJ+9OgRZs2aBVdXV5iZmcHb2xubN29WaPM8Y46MjET37t1hZWUFBwcHjBw5ElevXm2SeJKTk/H666/DxMQEnp6e2LZtW73j1TbuBw8eYPbs2fDy8oKZmRnc3Nzw4YcfoqioSGdxa3OtZYgIQ4YMUfk79LyvtXxQjDHGtHD48GFatGgR7du3jwDQ/v37FeozMzPJ1taWwsLC6OzZs5SZmUkHDhyg/Px8oU1wcDC1atWKEhIS6PTp09SrVy/q3bu3UP/kyRPq1KkTDRw4kM6dO0eHDx8mOzs7Cg8Pb5KYp0+fTm3btqWkpCTKysqiLVu2kJGRER04cEAnMQcEBFB0dDRdvHiR0tPTaejQoeTm5kaPHj1q1Hhu3rxJ5ubmFBoaSpcuXaKvv/6ajIyM6MiRI/WOWZu4L1y4QKNHj6aDBw9SZmYmJSQkULt27WjMmDE6i1ubay2zevVqGjJkSK3fIV1caxlOYBhjrAFUJQPjx4+nf/7zn2q3KSwsJGNjY4qNjRXKLl++TAAoLS2NiGoSDkNDQ8rLyxPaREVFkVgspoqKikaPuWPHjrRs2TKFstdff50WLVr0QsRcUFBAACglJaVR45k/fz517NhR4Vjjx4+ngICAZ4pXXdyq7Nmzh0QiEVVVVb0QcauL+dy5c9SyZUvKzc2t9Tuky5j5FhJjjDUCqVSKuLg4/O1vf0NAQAAcHBzQs2dPhe72M2fOoKqqCgMHDhTK2rdvDzc3N6SlpQEA0tLS0LlzZ4UnagcEBKC4uBgZGRmNHnfv3r1x8OBB/PnnnyAiJCUl4dq1a/D3938hYpbdYrG1tW3UeNLS0hT2IWsj28ezUo5bXRuxWIxmzZq9EHGrirm0tBQTJ07Exo0bVT5PTJcxcwLDGGONoKCgAI8ePcKKFSswePBgHDt2DKNGjcLo0aORkpICAMjLy4NIJKr1xGtHR0fk5eUJbeQ/DGT1srrG9vXXX8Pb2xuurq4QiUQYPHgwNm7cCF9fX53HLJVKMWfOHPTp0wedOnVq1HjUtSkuLkZZWVmDY1YXt7J79+7hs88+w/vvvy+U6TJudTHPnTsXvXv3xogRI1Rup8uY+VlIjDHWCKRSKQBgxIgRmDt3LgCga9euSE1NxebNm9GvXz9dhqfW119/jV9//RUHDx6Eu7s7Tpw4gZCQELi4uNT6q/l5CwkJwcWLF3Hy5EmdxlFfdcVdXFyMwMBAeHt7IyIi4vkGp4aqmA8ePIjExEScO3dOh5Gpxz0wjDHWCOzs7NCsWTN4e3srlHfo0EGYheTk5ITKykoUFhYqtMnPzxe6552cnGrNqJG9V9WF/yzKysqwcOFCrF69GsOHD0eXLl0wa9YsjB8/Hl9++aVOY541axYOHTqEpKQkuLq6CuWNFY+6NmKxGGZmZg2KWVPcMiUlJRg8eDCsrKywf/9+GBsbK5ybLuJWF3NiYiJu3LgBGxsbNGvWTLjVNWbMGPj5+ek0ZoATGMYYaxQikQjdu3evNQ312rVrcHd3BwD4+PjA2NgYCQkJQv3Vq1eRk5MDiUQCAJBIJLhw4QIKCgqENvHx8RCLxbWSo2dVVVWFqqoqGBoqfhQYGRkJPUrPO2YiwqxZs7B//34kJiaiTZs2CvWNFY9EIlHYh6yNbB/1VVfcQE3Pi7+/P0QiEQ4ePAhTU1OF+ucdd10xf/LJJzh//jzS09OFFwCsWbMG0dHROolZ+QQYY4xpoaSkhM6dO0fnzp0jALR69Wo6d+4c3bp1i4iI9u3bR8bGxrR161a6fv26MF30559/FvYRHBxMbm5ulJiYSKdPnyaJREISiUSol01L9ff3p/T0dDpy5AjZ29s3eBp1XTH369ePOnbsSElJSXTz5k2Kjo4mU1NT2rRpk05injlzJllbW1NycjLl5uYKr9LS0kaNRza1NywsjC5fvkwbN258pqm9dcVdVFREPXv2pM6dO1NmZqZCmydPnugkbm2utTKomUb9PK+1EMszbc0YY6+QpKQkAlDrFRQUJLT57rvvyNPTk0xNTem1116jH374QWEfZWVl9MEHH1Dz5s3J3NycRo0aRbm5uQptsrOzaciQIWRmZkZ2dnY0b948YaptY8ecm5tLkydPJhcXFzI1NSUvLy/66quvSCqV6iRmVbECoOjo6EaPJykpibp27UoikYg8PDwUjtHYcav7OQCgrKwsncStzbVWtY3yVPznfa1lDJ4GxBhjjDGmN3gMDGOMMcb0DicwjDHGGNM7nMAwxhhjTO9wAsMYY4wxvcMJDGOMMcb0DicwjDHGGNM7nMAwxhhjTO9wAsMYY4wxvcMJDGOMMcb0DicwjDHGGNM7nMAwxhhjTO/8P1Td6mXSx9UkAAAAAElFTkSuQmCC",
      "text/plain": [
       "<Figure size 640x480 with 2 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "fig, (ax1, ax2) = plt.subplots(1, 2)\n",
    "\n",
    "ax1.imshow(sim_fov0.model/1.9e18, interpolation='Nearest', \n",
    "           origin='lower', vmin=0, vmax=1, cmap='hot')\n",
    "ax1.set_xlim(2000,3400)\n",
    "ax1.set_ylim(3300,3550)\n",
    "ax1.set_title(\"Masked Simulation cutout\")\n",
    "\n",
    "ax2.imshow(sim_fov0_2.model/1.9e18, interpolation='Nearest', \n",
    "           origin='lower', vmin=0, vmax=1, cmap='hot')\n",
    "ax2.set_xlim(1500,2500)\n",
    "ax2.set_ylim(0,500)\n",
    "ax2.set_title(\"Cutout Close to Origin\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "seg-prac",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
